org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2

minecraft_version_range=[26.1.2]

neo_version=26.1.2.61-beta


loader_version_range=[1,)

## Mod Properties

mod_id=enhanced_ore_variety

mod_name=Mar Mar's Enhanced Ore Variety

mod_license=MIT Licence

mod_version=26.1.2-neoforge-3.0.0

mod_group_id=net.marmar.enhanced_ore_variety

mod_authors=Mar Mar

mod_description=Enjoy the overworld like a new player.\nWith Mar Mar's Enhanced Ore Variety, all ores have a Granite, Diorite, Andesite and Tuff variant\
  ready to be mined.
